import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chai Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <h2>Chai Nav Item</h2>
        {children}
    </>
  );
}
